### ISSUE TITLE
Old/slow validate promises override errors from new/fast promises

### ISSUE THREAD

**Issue by tjwallace** [final-form/final-form#147]
### What is the current behavior?

An older, longer running validation promise will override the error state from a newer, shorter running validation promise.

### What is the expected behavior?

Older validation promises are ignored and only the latest validation result is used.

### Sandbox Link

https://codesandbox.io/s/wy7z7q5zx5

In the username field, quickly enter any character and then delete it before the async validation can finish running. Notice the `Required` error briefly appears before being overridden by the async validation.

**Comment by erikras** [comment]
Too bad [promises aren't cancelable](https://www.infoworld.com/article/3153028/javascript/cancelable-javascript-promises-cancelled.html).

This _could_ maybe be fixed by keeping a unique integer id for each validation call, and keeping track of which ones have already returned for a given field, and ignoring ids that are `<` the last one returned, but it would be pretty darn complicated to do so.

I'm leaning towards not fixing this problem. 😕

**Comment by shrugs** [comment]
@erikras the `Rx#switchMap` property of validations is definitely in-scope for final-form, imo — older validations should not update the state because they operated on old data and necessarily lead to inconsistent state.

Allowing async validate functions to exit-early is definitely out of scope, but avoiding state updates from old promises is _definitely_ necessary.

For example, if you have a long-running async validator and then access `values` based on the `valid` prop like:

```ts
if (valid) {
  // ... do something to values.myValue, assuming that it's in the correct format
}
```

your code will throw an error when it attempts to operate on the _latest_ data that final-form incorrectly says is `valid`.

I expect this race condition pattern is pretty common, since it will show up in any validator that does something like:

```
const validate = (values) => {
  if (!isInCorrectFormat(values.myValue) {
    return { myValue: 'oh no!' }
  }

  const isValidRemotely = await fetchIsValidRemotely(values.myValue)
  if (!isValidRemotely) {
    return { myValue: 'not valid remotely!' }
  }
}
```

where the function by definition takes longer in some some cases over others and the race condition will almost always appear when going from a valid value to an invalid one.

---

without getting into the weeds of actually making this PR, I expect the feature is relatively straightforward to implement

on [L290](https://github.com/final-form/final-form/blob/master/src/FinalForm.js#L290), we should switch to using a record-level id (`const asyncValidationRecordPromiseKey = ++nextAsyncRecordValidationKey`)

then on [L292](https://github.com/final-form/final-form/blob/master/src/FinalForm.js#L292) we should make the `setError` call conditional on whether or not the promise is still the most recent one (`asyncValidationRecordPromiseKey === asyncValidationPromiseKey`) (i.e. if another async validation has started, the id will be incremented and we should discard this one)

the same process can be done for field-level validations

alternatively, another approach would be to _expect_ validate functions to throw an error, meaning that their result should be ignored. we would want to avoid calling `processErrors` as part of the `catch` when awaiting those promises. then callers can implement their own validation-id logic and do something like

```ts
if (latestValidation.current > myId) throw new Error('exit')
```

to bail (and even exit-early)

---

workaround:

unfortunately working around this (without modifying final-form directly) seems impossible, since `processErrors` is always called for a given promise meaning that even if you implement the id pattern and use it within your validation function, when you return `undefined` final-form will treat the form as valid, giving you the same behavior as above. If you `throw` from the validator, the same thing will happen, since [afterPromises](https://github.com/final-form/final-form/blob/master/src/FinalForm.js#L451) runs `processErrors` anyway

**Comment by shrugs** [comment]
@erikras I've implemented this feature as a PR https://github.com/final-form/final-form/pull/265

**Comment by erikras** [comment]
Published fix in [`v4.18.4`](https://github.com/final-form/final-form/releases/tag/v4.18.4).

**Comment by alexjsdev** [comment]
@shrugs you're the best! I couldn't update to past v4 of react-final-form because of a bug i was experiencing, and this release fixes that issue, so now i can update to the latest of both final-form and react-final-form!! thank you both for your time and effort on this!

p.s. @erikras special thank you for taking the time to debug with me via twitter DM! hope you're enjoying your indent  🌈 in vscode 😉

**Comment by shrugs** [comment]
thanks @alexjsdev <3 that means a lot! glad to help
