### ISSUE TITLE
Field with initial value of null is undirtyable

### ISSUE THREAD

**Issue by joebandenburg** [final-form/final-form#155]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

* Initialise a field to `null` using `initialValues`
* Type a value into the input
* Remove the value from the input
* The field and form is still marked as `dirty`

### What is the expected behavior?

After clearing the input the field and form are no longer marked as `dirty`.

### Sandbox Link

https://codesandbox.io/s/r05q8xl5n

Try entering a first name and then removing it again. Notice how the "Submit" button does not become disabled when the name is removed. Compare this behaviour to the last name field.

### What's your environment?

final-form: latest
react-final-form: latest 

### Other information

From the user's perspective the form has been reverted to its initial state but Final Form thinks the form is dirty.

I believe this happens because Final Form resets the value to `undefined` when the input is cleared. By default, `===` is used to determine dirty state and `null !== undefined`. I'm not sure what the correct solution is be here, but it seems that it should be addressed somehow as passing in `null` is probably not uncommon.

P.S. _undirtyable_ is definitely a word 🤔

**Comment by ncphillips** [comment]
Something seems to be wrong with CodeSandbox or `final-form`. The link you provided does not work for me, and neither does the one in the README. I added an [issue](https://github.com/final-form/final-form/issues/210).

Anyway, I think there is a significant enough difference between `null` and `''` to warrant not change the current default behavior. At my organization we use FinalForm to generate JSON/YAML files, and this distinction is pretty consequential.

Regardless, it is already possible for you to override this behaviour on a per field basis using the `isEqual` attribute:

```jsx
    <Form
      onSubmit={onSubmit}
      initialValues={{ firstName: null, stooge: 'larry', employed: false }}
      render={({ handleSubmit, form, submitting, pristine, values }) => (
        <form onSubmit={handleSubmit}>
          <div>
            <label>First Name</label>
            <Field
              name="firstName"
              component="input"
              type="text"
              placeholder="First Name"
              // Override here...
              isEqual={(prev, next) => prev == next}
            />
          </div>
 ```

If you often need this behaviour you could make a wrapper:

```jsx
const LooseField = props => (
  <Field isEqual={(prev, next) => prev == next} {...props} />
)
```

**Comment by erikras** [comment]
This is not a bug, but an intentional design decision, [explained here](https://github.com/final-form/final-form/blob/master/docs/faq.md#why-does--final-form-set-my--field-value-to-undefined).

@ncphillips is exactly right, that if you really need full control over dirty/pristine behavior, that is provided to you with the `isEquals` prop.

Fixing it to your expectations would require specifically remembering if the field was initialized as `""` or `null` when setting the value to `""`. It's potentially doable, but I don't think it's worth adding the extra logic to everyone's bundle.

Another option is for you to adopt `undefined` rather than `null` for your initialized value. I understand the subtle difference, but rarely find a need to use `null` in my daily coding.

**Comment by erikras** [comment]
Further reading: https://github.com/sindresorhus/meta/issues/7
