### ISSUE TITLE
form state becomes dirty when initial value is empty, and user interacting without actually changing the value 

### ISSUE THREAD

**Issue by marcusasplund** [final-form/final-form#463]
### What is the current behavior?

When initial value is an empty string, then the user types, then erases, the form state is dirty, though the form state is unchanged from initial state. 

### What is the expected behavior?

I expect the `form.getState().dirty` to be false when value has not changed from initial value

### Sandbox Link

[sandbox example](https://codesandbox.io/s/react-final-form-simple-example-forked-pwdonf?file=/index.js)

### What's your environment?

Latest final form

### Other information
none

**Comment by gertdreyer** [comment]
This is due to final form treating empty fields as `undefined` and the declaration of the initialValues as empty strings. 
Two options to remedy this. Declare initialValues as `undefined` or use and identity function as the parse prop on each field `parse={(val) => val}` .

This behavior is well documented in final-form/react-final-form#130 if you need more information. 

Dirty flag is working as expected as values != initialValues
